# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\main_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_KinectCapture(object):
    def setupUi(self, KinectCapture):
        KinectCapture.setObjectName("KinectCapture")
        KinectCapture.resize(1300, 1000)
        self.centralwidget = QtWidgets.QWidget(KinectCapture)
        self.centralwidget.setObjectName("centralwidget")
        self.KinectGraph = QtWidgets.QGraphicsView(self.centralwidget)
        self.KinectGraph.setGeometry(QtCore.QRect(10, 5, 1280, 720))
        self.KinectGraph.setObjectName("KinectGraph")
        self.StartCollect = QtWidgets.QPushButton(self.centralwidget)
        self.StartCollect.setGeometry(QtCore.QRect(720, 820, 211, 91))
        self.StartCollect.setObjectName("StartCollect")
        self.ResolutionBox = QtWidgets.QComboBox(self.centralwidget)
        self.ResolutionBox.setGeometry(QtCore.QRect(10, 740, 201, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ResolutionBox.setFont(font)
        self.ResolutionBox.setObjectName("ResolutionBox")
        self.ResolutionBox.addItem("")
        self.ResolutionBox.addItem("")
        self.ResolutionBox.addItem("")
        self.ResolutionBox.addItem("")
        self.ResolutionBox.addItem("")
        self.ResolutionBox.addItem("")
        self.ResolutionBox.addItem("")
        self.FPSBox = QtWidgets.QComboBox(self.centralwidget)
        self.FPSBox.setGeometry(QtCore.QRect(220, 740, 151, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.FPSBox.setFont(font)
        self.FPSBox.setObjectName("FPSBox")
        self.FPSBox.addItem("")
        self.FPSBox.addItem("")
        self.FPSBox.addItem("")
        self.FPSBox.addItem("")
        self.StartKinect = QtWidgets.QPushButton(self.centralwidget)
        self.StartKinect.setGeometry(QtCore.QRect(380, 740, 151, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.StartKinect.setFont(font)
        self.StartKinect.setObjectName("StartKinect")
        self.NoticeNoChange = QtWidgets.QLabel(self.centralwidget)
        self.NoticeNoChange.setGeometry(QtCore.QRect(10, 880, 531, 81))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.NoticeNoChange.setFont(font)
        self.NoticeNoChange.setObjectName("NoticeNoChange")
        self.FilePath = QtWidgets.QTextBrowser(self.centralwidget)
        self.FilePath.setGeometry(QtCore.QRect(730, 790, 191, 31))
        self.FilePath.setObjectName("FilePath")
        self.ChoosePath = QtWidgets.QPushButton(self.centralwidget)
        self.ChoosePath.setGeometry(QtCore.QRect(960, 790, 112, 34))
        self.ChoosePath.setObjectName("ChoosePath")
        self.CaptureTime = QtWidgets.QLabel(self.centralwidget)
        self.CaptureTime.setGeometry(QtCore.QRect(970, 850, 81, 18))
        self.CaptureTime.setText("")
        self.CaptureTime.setObjectName("CaptureTime")
        self.CapturedPicsNum = QtWidgets.QLabel(self.centralwidget)
        self.CapturedPicsNum.setGeometry(QtCore.QRect(970, 880, 81, 18))
        self.CapturedPicsNum.setObjectName("CapturedPicsNum")
        KinectCapture.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(KinectCapture)
        self.statusbar.setObjectName("statusbar")
        KinectCapture.setStatusBar(self.statusbar)

        self.retranslateUi(KinectCapture)
        QtCore.QMetaObject.connectSlotsByName(KinectCapture)

    def retranslateUi(self, KinectCapture):
        _translate = QtCore.QCoreApplication.translate
        KinectCapture.setWindowTitle(_translate("KinectCapture", "Kinect Capture by Van"))
        self.StartCollect.setText(_translate("KinectCapture", "开始采集"))
        self.ResolutionBox.setItemText(0, _translate("KinectCapture", "分辨率"))
        self.ResolutionBox.setItemText(1, _translate("KinectCapture", "3072P(4096*3072)"))
        self.ResolutionBox.setItemText(2, _translate("KinectCapture", "2160P(3840*2160)"))
        self.ResolutionBox.setItemText(3, _translate("KinectCapture", "1536P(2048*1536)"))
        self.ResolutionBox.setItemText(4, _translate("KinectCapture", "1440P(2560*1440)"))
        self.ResolutionBox.setItemText(5, _translate("KinectCapture", "1080P(1920*1080)"))
        self.ResolutionBox.setItemText(6, _translate("KinectCapture", "720P(1280*720)"))
        self.FPSBox.setItemText(0, _translate("KinectCapture", "帧数"))
        self.FPSBox.setItemText(1, _translate("KinectCapture", "30FPS"))
        self.FPSBox.setItemText(2, _translate("KinectCapture", "15FPS"))
        self.FPSBox.setItemText(3, _translate("KinectCapture", "5FPS"))
        self.StartKinect.setText(_translate("KinectCapture", "启动Kinect"))
        self.NoticeNoChange.setText(_translate("KinectCapture", "注意：一旦启动后无法更改！"))
        self.ChoosePath.setText(_translate("KinectCapture", "选择路径"))
        self.CapturedPicsNum.setText(_translate("KinectCapture", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    KinectCapture = QtWidgets.QMainWindow()
    ui = Ui_KinectCapture()
    ui.setupUi(KinectCapture)
    KinectCapture.show()
    sys.exit(app.exec_())
